config/routes.rb
Rails.application.routes.draw do
 
  get 'dashboard/index'
  
  get '/timeline', to: 'timeline#index' 

  get '/timeservice', to: 'time_service#index' 
  
  get 'git/index'

  root 'dashboard#index'

end

app/models/time_service.rb
class TimeService < ActiveRecord::Base
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
end

app/models/twitter_keywords.rb
class TwitterKeywords < ActiveRecord::Base
	
end

app/models/twitter_search.rb
# class TwitterSearch
# 	include ActiveModel::Model

# 	attribute :search, String
# 	attribute :is_rt, Boolean

# 	def persisted?
# 		false
# 	end

# 	def save
# 		$client.search("##{self.search} -rt", lang: "es").take(10)
# 	end
# end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/git_controller.rb
class GitController < ApplicationController
  
  def index

  	github = Github.new
  	starring = Github::Client::Activity::Starring.new
		
		if params[:search].blank?
			@search = 'carlosazaustre'
		else
			@search = params[:search]
		end
  	
  
  	@repos = github.repos.list user: "#{@search}"
  	@followers = github.users.followers.list "#{@search}"
  
  end

end

app/controllers/time_service_controller.rb
class TimeServiceController < ApplicationController

	def index
		t = Time.now
		
		h = t.strftime('%D').to_i
		m = t.strftime('%B').to_i
		s = t.strftime('%Y').to_i
		x = t.strftime('%x').to_i

		
		#TimeService.create(hours: h , minutes: m)
		@date = t.strftime('%x')
	end

end

app/controllers/timeline_controller.rb
class TimelineController < ApplicationController
  def index
  	@search = params[:search]

  	if @search.present?
  		TwitterKeywords.create(keyword: @search)
		end

  	@tweets = $client.search("##{@search} -rt", lang: "es").take(10)

  	
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/timeline_helper.rb
module TimelineHelper
end

app/views/dashboard/_timeline.html.erb
<%= form_tag timeline_index_path, method: :get, class: 'navbar-form pull-right' do %>
	<%= text_field_tag :search, @search, placeholder: 'hashtag...', style: 'width: 200px' %>
	<%= submit_tag "Search", class: 'btn btn-default' %>
<% end %>

<h2># Ruby</h2>

<ul class="list-group">
	<% @tweets.each do |tweet| %>
		<li class = "list-group-item"><span><%= tweet.user.screen_name %></span> | <%= tweet.text %>	</li>
	<% end %>	
</ul>

app/views/dashboard/_timeservice.html.erb
<%= @time %>

app/views/dashboard/index.html.erb
<div class="container">
	<h1 class="text-center">Dashboard</h1>

<!-- 	<%= link_to "TWITTER ", timeline_path  %>
	|
	<%= link_to "TIMESERVICE", timeservice_path  %> -->

<div class="row">
  <div class="col-sm-4">
    <%= cell(:time_service, @date) %>
  </div>
  <div class="col-sm-8">
    <%= cell(:timeline, @tweets) %>
  </div>
</div>

<%= cell(:github, @repos) %>

  <div class="row">
    <div class="col-sm-12">
    <hr>
      <a class="btn btn-primary" data-toggle="modal" href='#modal-id'>Add Widget</a>
	      <div class="modal fade" id="modal-id">
		      <div class="modal-dialog">
			      <div class="modal-content">
				      <div class="modal-header">
					      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					      <h4 class="modal-title">Choose Widget</h4>
				      </div>
				      <div class="modal-body">
				      <%= link_to "Twitter", timeline_path, class:"btn btn-primary" %>
				      <%= link_to "Time Service", timeservice_path, class:"btn btn-danger" %>
					
				      </div>
				      <div class="modal-footer">
					      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					      <!--<button type="button" class="btn btn-primary">Save</button> -->
				      </div>
			      </div>
		      </div>
	      </div>
    </div>
  </div>
</div>

app/views/git/index.html.erb
<div class="container">

	<div class="row">
		<div class="panel panel-default">
		  <div class="panel-body">
		  	<h1 class="text-center">Github Widget</h1>
		  </div>
	  	<div class="panel-footer">
	  		<h4 class="text-center panel-danger"><%= @search %></h4>
	  	</div>
		</div>
		
		<%= form_tag git_index_path, method: :get, class: 'navbar-form pull-right' do %>
			<%= text_field_tag :search, @search, placeholder: 'Github user...', class:'form-control' %>
			<%= submit_tag "Search", class: 'btn btn-default' %>
		<% end %>
	</div>
	<hr>
	
	<div class="row">
		<div class="col-xs-6 col-lg-6">
			<h4 class="breadcrumb">Repos & Stars</h4>
				<ul class="list-group">
					<% @repos.each do |repo| %>
						<li class="list-group-item">
							<h5><%= link_to repo.name, repo.html_url, target: "_blank" %></h5>
							<span class="badge"><%= repo.watchers %></span>
							<p><%= repo.description %></p>
							<p><%= link_to "Clone", repo.clone_url, target: "_blank" %></p>
						</li>
					<% end %>
				</ul>
		</div>

		<div class="row col-xs-6 col-lg-6">
			<h4 class="breadcrumb"><%= @followers.count %> Followers</h4>
			<% @followers.each do |follower| %>
			  <%= link_to follower.html_url, target: "_blank" do %>
				  <%= image_tag  (follower.avatar_url), class:"img-circle"%>
				<% end %>
			<% end %>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/time_service/index.html.erb
<div class="time">
	<p><%= @date %></p>
	<hr>
	<p id="reloj"></p>
</div>

<script>
	setInterval(showClock, 1000);
</script>

app/views/timeline/index.html.erb
<div class="container twitter">
<div class="row">
<%= form_tag timeline_path, method: :get, class: 'navbar-form pull-right' do %>
	<%= text_field_tag :search, @search, placeholder: 'hashtag...', class:"form-control text-center" %>
	<%= submit_tag "Search", class: 'btn btn-success' %>
<% end %>


</div>
	<ul class="list-group">
		<% @tweets.each do |tweet| %>
			<li class = "list-group-item"><span><%= tweet.user.screen_name %></span> | <%= tweet.text %>	</li>
		<% end %>	
	</ul>
</div>